version: '3'
services:
  shellcode:
    build:
      context: .
    working_dir: /home/pwn
    container_name: shellcode
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9003:9003"
    entrypoint: /etc/init.sh
